# Generated by Django 5.0.3 on 2024-03-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img', models.URLField()),
                ('featured_time', models.DateTimeField()),
                ('source_url', models.URLField()),
                ('categories', models.ManyToManyField(db_table='gift_category', related_name='+', to='categories.category')),
            ],
            options={
                'db_table': 'gift',
            },
        ),
    ]
