# Generated by Django 5.0.3 on 2024-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='featured_time',
            field=models.DateTimeField(null=True),
        ),
    ]
