# Generated by Django 5.0.3 on 2024-03-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name'),
        ('gifts', '0003_remove_gift_featured_time_gift_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='categories',
            field=models.ManyToManyField(db_table='gift_category', related_name='category_gifts', to='categories.category'),
        ),
    ]
