# Generated by Django 5.0.3 on 2024-03-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_name'),
        ('gifts', '0004_alter_gift_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='categories',
            field=models.ManyToManyField(to='categories.category'),
        ),
    ]
